spring:
  profiles:
    active: worker,persistence,external-local,common,domain,redis

server:
  port: 9000

logging:
  level:
    org.springframework.batch: DEBUG
    org.springframework.batch.core: DEBUG

