services:
  api:
    image: ${DOCKER_USERNAME}/chessladder-api:latest
    container_name: chessladder-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: api-prod,persistence-prod,external-prod,common,domain,redis-prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_JWT_ACCESS_TOKEN_SECRET: ${SPRING_JWT_ACCESS_TOKEN_SECRET}
      SPRING_JWT_ACCESS_TOKEN_EXPIRATION: ${SPRING_JWT_ACCESS_TOKEN_EXPIRATION}
      SPRING_JWT_REFRESH_TOKEN_SECRET: ${SPRING_JWT_REFRESH_TOKEN_SECRET}
      SPRING_JWT_REFRESH_TOKEN_EXPIRATION: ${SPRING_JWT_REFRESH_TOKEN_EXPIRATION}
      LICHESS_CLIENT_ID: ${LICHESS_CLIENT_ID}
      LICHESS_REDIRECT_URL: ${LICHESS_REDIRECT_URL}
      CHESSCOM_CLIENT_ID: ${CHESSCOM_CLIENT_ID}
      CHESSCOM_REDIRECT_URL: ${CHESSCOM_REDIRECT_URL}
      CLOUDFLARE_R2_ENDPOINT: ${CLOUDFLARE_R2_ENDPOINT}
      CLOUDFLARE_R2_ACCESS_KEY: ${CLOUDFLARE_R2_ACCESS_KEY}
      CLOUDFLARE_R2_SECRET_KEY: ${CLOUDFLARE_R2_SECRET_KEY}
      CLOUDFLARE_R2_BUCKET: ${CLOUDFLARE_R2_BUCKET}
      CLOUDFLARE_R2_CDN: ${CLOUDFLARE_R2_CDN}
      CLIENT_URL: ${CLIENT_URL}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}

  worker:
    image: ${DOCKER_USERNAME}/chessladder-worker:latest
    container_name: chessladder-worker
    restart: always
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: worker-prod,persistence-prod,external-prod,common,domain,redis-prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      SPRING_JWT_ACCESS_TOKEN_SECRET: ${SPRING_JWT_ACCESS_TOKEN_SECRET}
      SPRING_JWT_ACCESS_TOKEN_EXPIRATION: ${SPRING_JWT_ACCESS_TOKEN_EXPIRATION}
      SPRING_JWT_REFRESH_TOKEN_SECRET: ${SPRING_JWT_REFRESH_TOKEN_SECRET}
      SPRING_JWT_REFRESH_TOKEN_EXPIRATION: ${SPRING_JWT_REFRESH_TOKEN_EXPIRATION}
      LICHESS_CLIENT_ID: ${LICHESS_CLIENT_ID}
      LICHESS_REDIRECT_URL: ${LICHESS_REDIRECT_URL}
      CHESSCOM_CLIENT_ID: ${CHESSCOM_CLIENT_ID}
      CHESSCOM_REDIRECT_URL: ${CHESSCOM_REDIRECT_URL}
      CLOUDFLARE_R2_ENDPOINT: ${CLOUDFLARE_R2_ENDPOINT}
      CLOUDFLARE_R2_ACCESS_KEY: ${CLOUDFLARE_R2_ACCESS_KEY}
      CLOUDFLARE_R2_SECRET_KEY: ${CLOUDFLARE_R2_SECRET_KEY}
      CLOUDFLARE_R2_BUCKET: ${CLOUDFLARE_R2_BUCKET}
      CLOUDFLARE_R2_CDN: ${CLOUDFLARE_R2_CDN}
      CLIENT_URL: ${CLIENT_URL}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}