plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.chessmate'
version = '0.0.1-SNAPSHOT'
description = 'chessmate-domain'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

bootJar {
    enabled = false
}
jar {
    enabled = true
}



tasks.register("prepareKotlinBuildScriptModel"){}
// 코틀린 버그 해결을 위한 신의 계시

dependencies {

    implementation project(':chessmate-common')

}

tasks.named('test') {
    useJUnitPlatform()
}
