spring:
  config:
    activate:
      on-profile: api
  security:
    oauth2:
      client:
        registration:
          lichess:
            client-id: ChessLadder
            client-authentication-method: none #PCKE 자동 활성화 하기
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/oauth/lichess/callback
            scope:
              - "preference:read"
              - "email:read"
            client-name: Lichess
          chesscom:
            client-id: 0cb23ccc-127e-11f1-9e9f-011b3c0d4706
            client-authentication-method: none
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/oauth/chesscom/callback
            scope:
              - "openid"
              - "profile"
              - "email"
            client-name: Chess.com
        provider:
          lichess:
            authorization-uri: https://lichess.org/oauth
            token-uri: https://lichess.org/api/token
            user-name-attribute: id
          chesscom:
            authorization-uri: https://oauth.chess.com/authorize
            token-uri: https://oauth.chess.com/token
            user-name-attribute: sub # OIDC 표준 식별자
  application:
    name: ChessMate-api

  jackson:
    property-naming-strategy: SNAKE_CASE

  jwt:
    access-token:
      secret: chessMateGbswProjectAccessTokenSecret
      expiration: 10000
    refresh-token:
      secret: chessMateGbswProjectRefreshTokenSecret
      expiration: 604800000

cookie:
  domain: localhost

oauth:
  lichess:
    redirect-url: http://localhost:8080/api/oauth/callback

client:
  url: http://localhost:5173


cloudflare:
  r2:
    endpoint: https://8abcc1ccfb278ca2c5b3e8ba07623e9e.r2.cloudflarestorage.com
    accessKey: 599e880ffcface6a291030c9dbc2f0a1
    secretKey: 06ee2c6f82726bb26b97cf2fabbfafd8224f7073fd0c87d68a3cf3383ee4d903
    bucket: chessladder
    cdn: https://pub-1e7b1be2d4da472a936752a572ed0419.r2.dev


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG