spring:
  config:
    activate:
      on-profile: api-local
  application:
    name: ChessMate-api
  jackson:
    property-naming-strategy: SNAKE_CASE
  jwt:
    access-token:
      secret: chessMateGbswProjectAccessTokenSecret
      expiration: 3600000
    refresh-token:
      secret: chessMateGbswProjectRefreshTokenSecret
      expiration: 604800000

cookie:
  domain: localhost

client:
  url: http://localhost:5173

cloudflare:
  r2:
    endpoint: ${CLOUDFLARE_R2_ENDPOINT:https://8abcc1ccfb278ca2c5b3e8ba07623e9e.r2.cloudflarestorage.com}
    accessKey: ${CLOUDFLARE_R2_ACCESS_KEY:599e880ffcface6a291030c9dbc2f0a1}
    secretKey: ${CLOUDFLARE_R2_SECRET_KEY:06ee2c6f82726bb26b97cf2fabbfafd8224f7073fd0c87d68a3cf3383ee4d903}
    bucket: ${CLOUDFLARE_R2_BUCKET:chessladder}
    cdn: ${CLOUDFLARE_R2_CDN:https://pub-1e7b1be2d4da472a936752a572ed0419.r2.dev}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.apache.coyote.http11.Http11Processor: DEBUG
    org.springframework.security.oauth2.client.oidc.authentication: TRACE
    org.springframework.security.oauth2.client.web: TRACE
    org.springframework.session: DEBUG
    org.apache.catalina.session: DEBUG
    org.springframework.security.web.context: DEBUG
    org.springframework.security.web.authentication.HttpSessionAuthenticationStrategy: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true